services:
  rtbgen:
    build: .
    env_file: .env
    ports:
      - "${PORT}:8080"
    volumes:
      - ./data:/app/data
    command:
      - -port=8080
      - -tasks-file=${TASKS_FILE}
      - -out-dir=${OUT_DIR}
      - -scheduler-interval=${SCHEDULER_INTERVAL}
      - -mmdb=${MMDB_PATH}
      - -bbox=${BBOX_MAX_LAT},${BBOX_MAX_LON},${BBOX_MIN_LAT},${BBOX_MIN_LON}
    restart: unless-stopped
